/**
 * Open-Meteo WMO Weather Interpretation Code Mapping
 * Maps numerical weather codes (0..99) to standardized condition metadata,
 * icons, human-readable labels, and baseline severity indicators.
 */

export interface WeatherCodeInfo {
  code: number;
  condition: string;
  label: string;
  iconKey: string;
  isPrecipitation: boolean;
  isRain: boolean;
  isSnow: boolean;
  isThunderstorm: boolean;
  isFog: boolean;
  isFreezing: boolean;
  severityBaseline: 'info' | 'moderate' | 'high' | 'extreme';
}

export const OPEN_METEO_WEATHER_CODE_MAP: Record<number, WeatherCodeInfo> = {
  0: {
    code: 0,
    condition: 'CLEAR',
    label: 'Clear Sky',
    iconKey: 'sun',
    isPrecipitation: false,
    isRain: false,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  1: {
    code: 1,
    condition: 'MAINLY_CLEAR',
    label: 'Mainly Clear',
    iconKey: 'sun',
    isPrecipitation: false,
    isRain: false,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  2: {
    code: 2,
    condition: 'PARTLY_CLOUDY',
    label: 'Partly Cloudy',
    iconKey: 'cloud-sun',
    isPrecipitation: false,
    isRain: false,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  3: {
    code: 3,
    condition: 'OVERCAST',
    label: 'Overcast',
    iconKey: 'cloud',
    isPrecipitation: false,
    isRain: false,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  45: {
    code: 45,
    condition: 'FOG',
    label: 'Fog',
    iconKey: 'haze',
    isPrecipitation: false,
    isRain: false,
    isSnow: false,
    isThunderstorm: false,
    isFog: true,
    isFreezing: false,
    severityBaseline: 'moderate',
  },
  48: {
    code: 48,
    condition: 'DEPOSITING_RIME_FOG',
    label: 'Freezing Fog',
    iconKey: 'haze',
    isPrecipitation: false,
    isRain: false,
    isSnow: false,
    isThunderstorm: false,
    isFog: true,
    isFreezing: true,
    severityBaseline: 'high',
  },
  51: {
    code: 51,
    condition: 'LIGHT_DRIZZLE',
    label: 'Light Drizzle',
    iconKey: 'cloud-drizzle',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  53: {
    code: 53,
    condition: 'MODERATE_DRIZZLE',
    label: 'Moderate Drizzle',
    iconKey: 'cloud-drizzle',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  55: {
    code: 55,
    condition: 'DENSE_DRIZZLE',
    label: 'Dense Drizzle',
    iconKey: 'cloud-drizzle',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'moderate',
  },
  56: {
    code: 56,
    condition: 'LIGHT_FREEZING_DRIZZLE',
    label: 'Light Freezing Drizzle',
    iconKey: 'cloud-hail',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'moderate',
  },
  57: {
    code: 57,
    condition: 'DENSE_FREEZING_DRIZZLE',
    label: 'Dense Freezing Drizzle',
    iconKey: 'cloud-hail',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'high',
  },
  61: {
    code: 61,
    condition: 'SLIGHT_RAIN',
    label: 'Slight Rain',
    iconKey: 'cloud-rain',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  63: {
    code: 63,
    condition: 'MODERATE_RAIN',
    label: 'Moderate Rain',
    iconKey: 'cloud-rain',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'moderate',
  },
  65: {
    code: 65,
    condition: 'HEAVY_RAIN',
    label: 'Heavy Rain',
    iconKey: 'cloud-rain-wind',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'high',
  },
  66: {
    code: 66,
    condition: 'LIGHT_FREEZING_RAIN',
    label: 'Light Freezing Rain',
    iconKey: 'cloud-hail',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'moderate',
  },
  67: {
    code: 67,
    condition: 'HEAVY_FREEZING_RAIN',
    label: 'Heavy Freezing Rain',
    iconKey: 'cloud-hail',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'high',
  },
  71: {
    code: 71,
    condition: 'SLIGHT_SNOW',
    label: 'Slight Snowfall',
    iconKey: 'snowflake',
    isPrecipitation: true,
    isRain: false,
    isSnow: true,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'moderate',
  },
  73: {
    code: 73,
    condition: 'MODERATE_SNOW',
    label: 'Moderate Snowfall',
    iconKey: 'snowflake',
    isPrecipitation: true,
    isRain: false,
    isSnow: true,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'high',
  },
  75: {
    code: 75,
    condition: 'HEAVY_SNOW',
    label: 'Heavy Snowfall',
    iconKey: 'snowflake',
    isPrecipitation: true,
    isRain: false,
    isSnow: true,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'extreme',
  },
  77: {
    code: 77,
    condition: 'SNOW_GRAINS',
    label: 'Snow Grains',
    iconKey: 'snowflake',
    isPrecipitation: true,
    isRain: false,
    isSnow: true,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'moderate',
  },
  80: {
    code: 80,
    condition: 'SLIGHT_RAIN_SHOWERS',
    label: 'Slight Rain Showers',
    iconKey: 'cloud-rain',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'info',
  },
  81: {
    code: 81,
    condition: 'MODERATE_RAIN_SHOWERS',
    label: 'Moderate Rain Showers',
    iconKey: 'cloud-rain',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'moderate',
  },
  82: {
    code: 82,
    condition: 'VIOLENT_RAIN_SHOWERS',
    label: 'Violent Rain Showers',
    iconKey: 'cloud-rain-wind',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: false,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'high',
  },
  85: {
    code: 85,
    condition: 'SLIGHT_SNOW_SHOWERS',
    label: 'Slight Snow Showers',
    iconKey: 'snowflake',
    isPrecipitation: true,
    isRain: false,
    isSnow: true,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'moderate',
  },
  86: {
    code: 86,
    condition: 'HEAVY_SNOW_SHOWERS',
    label: 'Heavy Snow Showers',
    iconKey: 'snowflake',
    isPrecipitation: true,
    isRain: false,
    isSnow: true,
    isThunderstorm: false,
    isFog: false,
    isFreezing: true,
    severityBaseline: 'high',
  },
  95: {
    code: 95,
    condition: 'THUNDERSTORM',
    label: 'Thunderstorm',
    iconKey: 'cloud-lightning',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: true,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'high',
  },
  96: {
    code: 96,
    condition: 'THUNDERSTORM_SLIGHT_HAIL',
    label: 'Thunderstorm with Slight Hail',
    iconKey: 'cloud-lightning',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: true,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'high',
  },
  99: {
    code: 99,
    condition: 'THUNDERSTORM_HEAVY_HAIL',
    label: 'Thunderstorm with Heavy Hail',
    iconKey: 'cloud-lightning',
    isPrecipitation: true,
    isRain: true,
    isSnow: false,
    isThunderstorm: true,
    isFog: false,
    isFreezing: false,
    severityBaseline: 'extreme',
  },
};

export function getWeatherCodeInfo(code?: number): WeatherCodeInfo {
  if (code === undefined || code === null || !(code in OPEN_METEO_WEATHER_CODE_MAP)) {
    return {
      code: code ?? 0,
      condition: 'UNKNOWN',
      label: 'Weather Condition',
      iconKey: 'cloud',
      isPrecipitation: false,
      isRain: false,
      isSnow: false,
      isThunderstorm: false,
      isFog: false,
      isFreezing: false,
      severityBaseline: 'info',
    };
  }
  return OPEN_METEO_WEATHER_CODE_MAP[code];
}
