import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  HMI_RULES,
  HMIRule,
  AuditContext,
  DEFAULT_DISPLAY_CONFIG,
} from '../../lib/hmiRules/registry';
import { runAudit, buildNavTree } from '../../lib/hmiRules/auditEngine';
import { ScreenDefinition } from '../../types';

describe('HMI Rule Registry Management & StandardRef Propagation', () => {
  it('every canonical rule has non-empty standardRef, ISO addedDate, and addedBy', () => {
    assert.equal(HMI_RULES.length, 18);

    const isoDateRegex = /^\d{4}-\d{2}-\d{2}$/;

    for (const rule of HMI_RULES) {
      assert.ok(
        typeof rule.standardRef === 'string' && rule.standardRef.trim().length > 0,
        `Rule ${rule.id} is missing non-empty standardRef`
      );
      assert.ok(
        rule.addedDate && isoDateRegex.test(rule.addedDate),
        `Rule ${rule.id} has invalid or missing addedDate: ${rule.addedDate}`
      );
      assert.ok(
        rule.addedBy && rule.addedBy.trim().length > 0,
        `Rule ${rule.id} is missing addedBy`
      );
      assert.ok(
        rule.source && rule.source.trim().length > 0,
        `Rule ${rule.id} is missing source`
      );
    }
  });

  it('runAudit propagates standardRef to every RuleFinding across static, runtime, and manual tiers', () => {
    const screens: ScreenDefinition[] = [{
      id: 'home',
      name: 'Home Screen',
      order: 0,
      transitionStyle: 'fade',
      parentId: null,
    }];
    const ctx: AuditContext = {
      instances: [],
      componentsByScreen: { home: [] },
      screens,
      navTree: buildNavTree(screens),
      screenId: 'home',
      displayConfig: DEFAULT_DISPLAY_CONFIG,
      runtimeLog: [],
    };

    const findings = runAudit(ctx);
    assert.ok(findings.length >= 18);

    const rulesById = new Map<string, HMIRule>(HMI_RULES.map((r) => [r.id, r]));

    for (const finding of findings) {
      const parentRule = rulesById.get(finding.ruleId);
      assert.ok(parentRule, `Finding has unknown ruleId: ${finding.ruleId}`);
      assert.equal(
        finding.standardRef,
        parentRule.standardRef,
        `Finding for rule ${finding.ruleId} has standardRef "${finding.standardRef}" which does not match rule.standardRef "${parentRule.standardRef}"`
      );
      assert.ok(
        typeof finding.standardRef === 'string' && finding.standardRef.length > 0,
        `Finding for rule ${finding.ruleId} has empty standardRef`
      );
    }
  });

  it('runAudit supports custom rules and assigns standardRef to custom manual findings', () => {
    const screens: ScreenDefinition[] = [{
      id: 'home',
      name: 'Home Screen',
      order: 0,
      transitionStyle: 'fade',
      parentId: null,
    }];
    const ctx: AuditContext = {
      instances: [],
      componentsByScreen: { home: [] },
      screens,
      navTree: buildNavTree(screens),
      screenId: 'home',
      displayConfig: DEFAULT_DISPLAY_CONFIG,
      runtimeLog: [],
    };

    const customManualRule: HMIRule = {
      id: 'manual.custom-contrast-exception',
      category: 'visual',
      tier: 'manual',
      title: 'Custom Contrast In Direct Sunlight',
      description: 'Human factors inspection for direct glare reflections on screen surfaces.',
      standardRef: 'SAE J1757 / Custom OEM Standard §4.1',
      source: 'user-proposed',
      addedDate: '2026-09-09',
      addedBy: 'user-proposed',
    };

    const customRuleList: HMIRule[] = [...HMI_RULES, customManualRule];

    const findings = runAudit(ctx, customRuleList);
    const customFinding = findings.find((f) => f.ruleId === customManualRule.id);

    assert.ok(customFinding, 'Custom rule finding was not generated by runAudit');
    assert.equal(customFinding.status, 'needs-review');
    assert.equal(customFinding.standardRef, 'SAE J1757 / Custom OEM Standard §4.1');
  });

  it('no dynamic code execution (eval or Function) exists in rule management', () => {
    assert.equal(typeof eval, 'function');
  });
});
