import { LibraryTask, TestDefinition, FeedbackQuestion } from './types';

export const BUILTIN_TASK_LIBRARY: LibraryTask[] = [
  {
    id: 'task-speed-increase',
    name: 'Increase speed',
    description: 'Increase vehicle speed to at least 65 mph using the Speedometer on the display.',
    targetScreen: 'home',
    targetComponent: 'speed',
    criteria: {
      type: 'state_field',
      field: 'speed',
      operator: '>=',
      expectedValue: 65,
    },
    setup: [{ kind: 'vehicleState', field: 'speed', value: 0 }],
    timeLimitSeconds: 30,
    points: 100,
    category: 'driving',
    isBuiltin: true,
  },
  {
    id: 'task-diagnostic-report',
    name: 'Send Diagnostic Report',
    description: 'Locate the Send Diagnostics widget on the Home screen and send the diagnostic report to the service center.',
    targetScreen: 'home',
    targetComponent: 'sendToServiceCenter',
    criteria: {
      type: 'action_event',
      field: 'sendDiagnosticReport',
      operator: '=',
      expectedValue: true,
    },
    setup: [{ kind: 'activeView', field: 'activeView', value: 'home' }],
    timeLimitSeconds: 45,
    points: 100,
    category: 'diagnostics',
    isBuiltin: true,
  },
  {
    id: 'task-battery-unit',
    name: 'Change battery % to miles',
    description: 'Tap the Battery readout to toggle the display unit from percentage to remaining range in miles.',
    targetScreen: 'home',
    targetComponent: 'battery',
    criteria: {
      type: 'action_event',
      field: 'changeBatteryUnit',
      operator: '=',
      expectedValue: 'miles',
    },
    setup: [{ kind: 'componentProp', component: 'battery', field: 'displayUnit', value: 'percent' }],
    timeLimitSeconds: 30,
    points: 75,
    category: 'driving',
    isBuiltin: true,
  },
  {
    id: 'task-change-temperature',
    name: 'Change temperature',
    description: 'Adjust the cabin climate temperature to 72°F using the temperature slider or stepper.',
    targetScreen: 'home',
    targetComponent: 'climateTemp',
    criteria: {
      type: 'climate_field',
      field: 'driverTemp',
      operator: '=',
      expectedValue: 72,
    },
    setup: [{ kind: 'climateState', field: 'driverTemp', value: 68 }],
    timeLimitSeconds: 30,
    points: 75,
    category: 'climate',
    isBuiltin: true,
  },
  {
    id: 'task-drive-mode',
    name: 'Change drive mode',
    description: 'Open the Drive Mode Selector and change the vehicle driving mode to SPORT.',
    targetScreen: 'home',
    targetComponent: 'driveMode',
    criteria: {
      type: 'state_field',
      field: 'driveMode',
      operator: '=',
      expectedValue: 'Sport',
    },
    setup: [{ kind: 'vehicleState', field: 'driveMode', value: 'Normal' }],
    timeLimitSeconds: 30,
    points: 100,
    category: 'driving',
    isBuiltin: true,
  },
  {
    id: 'task-change-music',
    name: 'Change music',
    description: 'Open the Media Player and select a track or start playback.',
    targetScreen: 'media',
    targetComponent: 'media',
    criteria: {
      type: 'action_event',
      field: 'playTrack',
      operator: '=',
      expectedValue: true,
    },
    setup: [{ kind: 'activeView', field: 'activeView', value: 'media' }],
    timeLimitSeconds: 40,
    points: 100,
    category: 'media',
    isBuiltin: true,
  },
  {
    id: 'task-dial-phone',
    name: 'Dial phone number',
    description: 'Open the Phone Keypad and place a call to 555-123-4567.',
    targetScreen: 'phone',
    targetComponent: 'phoneDialPad',
    criteria: {
      type: 'action_event',
      field: 'dialPhone',
      operator: 'includes',
      expectedValue: '5551234567',
    },
    setup: [{ kind: 'activeView', field: 'activeView', value: 'phone' }],
    timeLimitSeconds: 45,
    points: 100,
    category: 'phone',
    isBuiltin: true,
  },
  {
    id: 'task-weather-radar',
    name: 'View weather radar',
    description: 'Switch to the Weather screen and open the full live weather radar view.',
    targetScreen: 'weather-radar',
    targetComponent: 'weather',
    criteria: {
      type: 'screen_navigate',
      field: 'activeView',
      operator: '=',
      expectedValue: 'weather-radar',
    },
    setup: [{ kind: 'activeView', field: 'activeView', value: 'weather' }],
    timeLimitSeconds: 30,
    points: 75,
    category: 'navigation',
    isBuiltin: true,
  },
  {
    id: 'task-search-destination',
    name: 'Search for destination',
    description: 'Navigate to Navigation and search for a destination or coffee shop.',
    targetScreen: 'navigation',
    targetComponent: 'navSearch',
    criteria: {
      type: 'action_event',
      field: 'searchDestination',
      operator: '!=',
      expectedValue: '',
    },
    setup: [{ kind: 'activeView', field: 'activeView', value: 'navigation' }],
    timeLimitSeconds: 45,
    points: 75,
    category: 'navigation',
    isBuiltin: true,
  },
  {
    id: 'task-plan-route',
    name: 'Plan route',
    description: 'Select a saved favorite or destination and start active trip route guidance.',
    targetScreen: 'navigation',
    targetComponent: 'navFavorites',
    criteria: {
      type: 'trip_guidance',
      operator: '=',
      expectedValue: true,
    },
    setup: [{ kind: 'activeView', field: 'activeView', value: 'navigation' }],
    timeLimitSeconds: 45,
    points: 100,
    category: 'navigation',
    isBuiltin: true,
  },
  {
    id: 'task-open-navigation',
    name: 'Open navigation',
    description: 'Switch from the current screen to the primary Navigation Map view.',
    targetScreen: 'navigation',
    targetComponent: 'map',
    criteria: {
      type: 'screen_navigate',
      field: 'activeView',
      operator: '=',
      expectedValue: 'navigation',
    },
    setup: [{ kind: 'activeView', field: 'activeView', value: 'home' }],
    timeLimitSeconds: 20,
    points: 50,
    category: 'navigation',
    isBuiltin: true,
  },
  {
    id: 'task-seat-climate',
    name: 'Adjust seat climate',
    description: 'Access seat climate controls and turn on driver seat heating or cooling.',
    targetScreen: 'home',
    targetComponent: 'climateSeats',
    criteria: {
      type: 'climate_field',
      field: 'driverSeatHeat',
      operator: '>',
      expectedValue: 0,
    },
    setup: [{ kind: 'climateState', field: 'driverSeatHeat', value: 0 }],
    timeLimitSeconds: 30,
    points: 75,
    category: 'climate',
    isBuiltin: true,
  },
  {
    id: 'task-media-source',
    name: 'Select media source',
    description: 'Switch the active music streaming service to Spotify.',
    targetScreen: 'media',
    targetComponent: 'media',
    criteria: {
      type: 'media_service',
      field: 'selectedMusicService',
      operator: '=',
      expectedValue: 'Spotify',
    },
    setup: [
      { kind: 'componentProp', component: 'media', field: 'service', value: 'Apple Music' },
      { kind: 'activeView', field: 'activeView', value: 'media' },
    ],
    timeLimitSeconds: 30,
    points: 75,
    category: 'media',
    isBuiltin: true,
  },
];

export const DEFAULT_FEEDBACK_QUESTIONS: FeedbackQuestion[] = [
  {
    id: 'fq-ease-of-use',
    prompt: 'How easy was it to find and interact with the requested vehicle controls?',
    type: 'rating',
    required: true,
  },
  {
    id: 'fq-visual-clarity',
    prompt: 'How would you rate the visual clarity and responsiveness of the infotainment displays?',
    type: 'rating',
    required: true,
  },
  {
    id: 'fq-distraction-level',
    prompt: 'Did any control require excessive attention or feel distracting while driving?',
    type: 'choice',
    options: ['Not distracting at all', 'Slightly distracting', 'Moderately distracting', 'Highly distracting'],
    required: false,
  },
  {
    id: 'fq-comments',
    prompt: 'Any specific feedback or difficulties experienced during this session?',
    type: 'text',
    required: false,
  },
];

export const INITIAL_TESTS: TestDefinition[] = [
  {
    id: 'test-baseline-infotainment-usability',
    name: 'Infotainment Usability Baseline Alpha',
    goal: 'Evaluate baseline driver interaction time and distraction levels across core vehicle speed, driving mode, climate, and media controls.',
    notes: 'Primary benchmark test for new infotainment releases. Targets essential vehicle interactions.',
    tasks: [
      {
        ...BUILTIN_TASK_LIBRARY[0], // Increase speed
        instanceId: 'inst-task-1',
        libraryTaskId: BUILTIN_TASK_LIBRARY[0].id,
        order: 0,
      },
      {
        ...BUILTIN_TASK_LIBRARY[4], // Change drive mode
        instanceId: 'inst-task-2',
        libraryTaskId: BUILTIN_TASK_LIBRARY[4].id,
        order: 1,
      },
      {
        ...BUILTIN_TASK_LIBRARY[3], // Change temperature
        instanceId: 'inst-task-3',
        libraryTaskId: BUILTIN_TASK_LIBRARY[3].id,
        order: 2,
      },
      {
        ...BUILTIN_TASK_LIBRARY[2], // Change battery % to miles
        instanceId: 'inst-task-4',
        libraryTaskId: BUILTIN_TASK_LIBRARY[2].id,
        order: 3,
      },
      {
        ...BUILTIN_TASK_LIBRARY[1], // Send Diagnostic Report
        instanceId: 'inst-task-5',
        libraryTaskId: BUILTIN_TASK_LIBRARY[1].id,
        order: 4,
      },
    ],
    feedbackQuestions: DEFAULT_FEEDBACK_QUESTIONS,
    createdAt: 1774483200000,
    updatedAt: 1774483200000,
  },
  {
    id: 'test-media-navigation-suite',
    name: 'Infotainment & Media Experience',
    goal: 'Measure user capability to navigate between applications, switch media services, play tracks, and initiate calls.',
    notes: 'Secondary experience test focused on media playback and phone communications.',
    tasks: [
      {
        ...BUILTIN_TASK_LIBRARY[12], // Select media source
        instanceId: 'inst-task-6',
        libraryTaskId: BUILTIN_TASK_LIBRARY[12].id,
        order: 0,
      },
      {
        ...BUILTIN_TASK_LIBRARY[5], // Change music
        instanceId: 'inst-task-7',
        libraryTaskId: BUILTIN_TASK_LIBRARY[5].id,
        order: 1,
      },
      {
        ...BUILTIN_TASK_LIBRARY[6], // Dial phone number
        instanceId: 'inst-task-8',
        libraryTaskId: BUILTIN_TASK_LIBRARY[6].id,
        order: 2,
      },
      {
        ...BUILTIN_TASK_LIBRARY[7], // View weather radar
        instanceId: 'inst-task-9',
        libraryTaskId: BUILTIN_TASK_LIBRARY[7].id,
        order: 3,
      },
    ],
    feedbackQuestions: DEFAULT_FEEDBACK_QUESTIONS,
    createdAt: 1774483200000,
    updatedAt: 1774483200000,
  },
  {
    id: 'test-navigation-trip-planning',
    name: 'Navigation & Trip Planning Usability',
    goal: 'Test accessibility and ease of searching for destinations, initiating route guidance, and monitoring weather radar.',
    notes: 'Navigation specific study focusing on route guidance initiation and map interaction.',
    tasks: [
      {
        ...BUILTIN_TASK_LIBRARY[10], // Open navigation
        instanceId: 'inst-task-10',
        libraryTaskId: BUILTIN_TASK_LIBRARY[10].id,
        order: 0,
      },
      {
        ...BUILTIN_TASK_LIBRARY[9], // Plan route
        instanceId: 'inst-task-11',
        libraryTaskId: BUILTIN_TASK_LIBRARY[9].id,
        order: 1,
      },
      {
        ...BUILTIN_TASK_LIBRARY[7], // View weather radar
        instanceId: 'inst-task-12',
        libraryTaskId: BUILTIN_TASK_LIBRARY[7].id,
        order: 2,
      },
    ],
    feedbackQuestions: DEFAULT_FEEDBACK_QUESTIONS,
    createdAt: 1774483200000,
    updatedAt: 1774483200000,
  },
];
